### ISSUE TITLE
Sugerencia de diseño

### ISSUE THREAD

**Issue by UrielBove** [pdepjm/2024-tp0-presentacion-Noise-arch#1]
Buenas, me gustó mucho tu presentación, muy bien usados los diferentes diseños para la presentación.
Lo único que podría recomendar es borrar el texto: "2024-tp0-presentacion-Noise-arch created by GitHub Classroom" que está debajo del título, ya que es repetitivo. Saludos!

**Comment by nooiise** [comment]
¡Gracias por la sugerencia! Ya está actualizado.
