### ISSUE TITLE
Achicar console.log

### ISSUE THREAD

**Issue by SantiagoGimenez01** [pdepjm/2024-tp0-presentacion-Noise-arch#2]
Podrías usar mas console.log para poner el mismo contenido de la presentación así no queda tan larga la línea de código y se evita usar la barra de desplazamiento para leer el renglón entero.

**Comment by nooiise** [comment]
¡Hola! Gracias por tu sugerencia, se me ocurrió usar backticks para solucionar el tema del scrollbar.
